#**Theoretical Questions:**

## **1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations?**




NumPy is a fundamental library in Python that significantly enhances its capabilities for scientific computing and data analysis. Below is an overview of its purpose, advantages, and how it improves numerical operations in Python


##**Purpose of NumPy**

NumPy, short for Numerical Python, is primarily designed to support efficient numerical computations. It provides a powerful array object, known as ndarray, which allows for the storage and manipulation of large datasets. This capability makes it an essential tool for various scientific applications, including:
* **Mathematical Operations:** NumPy facilitates complex mathematical operations on arrays and matrices, enabling users to perform calculations with ease.
* **Data Analysis:** The library supports data manipulation and analysis, making it suitable for tasks in data science and machine learning.


##**Advantages of NumPy**
A. **performance**

NumPy arrays are optimized for performance. They use contiguous memory blocks, which leads to faster data access compared to Python lists. Operations on NumPy arrays are executed at compiled C speed, making them significantly faster than equivalent operations performed using native Python constructs.

B. **Memory Efficiency**

NumPy arrays consume less memory than Python lists because they store elements of the same type in a contiguous block of memory. This efficiency is crucial when working with large datasets, as it reduces overhead and enhances performance


C. **Rich Functionality**

The library offers a comprehensive suite of mathematical functions (often referred to as universal functions or ufuncs) that operate element-wise on arrays. This includes functions for trigonometric calculations, statistical analysis, linear algebra, and more. Users can perform operations like addition, subtraction, multiplication, and division with simple syntax, either using operators or dedicated functions (e.g., `np.add`, `np.subtract`).

D. **Broadcasting**

One of NumPy's standout features is broadcasting, which allows operations on arrays of different shapes without the need for explicit looping. This feature simplifies code and enhances readability by automatically aligning the shapes of the arrays involved in operations.

E. **Interoperability**

NumPy integrates seamlessly with other libraries such as Pandas (for data manipulation), Matplotlib (for plotting), and SciPy (for scientific computing), making it a cornerstone of the scientific computing ecosystem in Python.

F. **Advanced Indexing and Slicing**

NumPy supports advanced indexing techniques that allow users to extract or manipulate subsets of data efficiently. This includes boolean indexing and multidimensional slicing, which provide powerful tools for data analysis.



**Enhancements to Python's Numerical Capabilities**

NumPy transforms Python into a robust environment for numerical computations by:
* Providing a high-performance array object (`ndarray`) that can handle large datasets efficiently.
* Enabling vectorized operations that eliminate the need for explicit loops, thus speeding up computations.
* Offering extensive mathematical functions that simplify complex calculations.
* Supporting advanced features like broadcasting and sophisticated indexing methods that enhance data manipulation capabilities.

##**2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the other?**


**Comparing np.mean() and np.average() in NumPy**

NumPy provides two functions for calculating the average value of an array: `np.mean()` and `np.average()`. While both functions seem to serve the same purpose, there are subtle differences between them.

**np.mean()**

`np.mean()` is a simple function that calculates the arithmetic mean of an array. It takes an array as input and returns the mean value. The arithmetic mean is calculated by summing all the elements in the array and dividing the result by the total number of elements.

**np.average()**

`np.average()` is a more versatile function that calculates the weighted average of an array. It takes two optional arguments: weights and returned. The weights argument allows us to specify a weight for each element in the array, enabling weighted averaging. The returned argument determines whether to return the average value or a tuple containing the average and the sum of weights.


**Key differences:**

**Weighted Averaging:** `np.average()` supports weighted averaging, while `np.mean()` does not.

**Optional Arguments:** `np.average()` has two optional arguments (weights and returned), whereas `np.mean()` has no optional arguments.

**Default Behavior:** `np.mean()` always returns the arithmetic mean, whereas `np.average()` returns the weighted average if weights are provided, and the arithmetic mean otherwise.
When to use each:

**np.mean():**
* When we need to calculate the simple arithmetic mean of an array.
* When we don't need to consider weights or biases in the averaging process.

**np.average():**
* When we need to calculate a weighted average, such as when dealing with data data that has varying importance or reliability.
* When we need more control over the averaging process, such as specifying weights or returning additional information.

## **3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D arrays.**

Reversing a NumPy array can be accomplished using various methods, each suitable for different scenarios. Below are the primary methods to reverse both 1D and 2D arrays, along with examples.

**Methods for Reversing a NumPy Array**

a. **Using Slicing**

Slicing is a straightforward method to reverse an array by specifying a step of -1.

Example for 1D Array


In [ ]:
import numpy as np

arr1d = np.array([1, 2, 3, 4, 5])
reversed1d = arr1d[::-1]

print("Original 1D array:", arr1d)
print("Reversed 1D array:", reversed1d)

Original 1D array: [1 2 3 4 5]
Reversed 1D array: [5 4 3 2 1]


b. **Using `np.flip()`**

The `np.flip()` function reverses the order of elements along the specified axis.

Example for 1D Array

In [ ]:
import numpy as np

arr1d = np.array([1, 2, 3, 4, 5])
reversed1d = np.flip(arr1d)

print("Reversed using np.flip():", reversed1d)

Reversed using np.flip(): [5 4 3 2 1]


c. **Using `np.flipud()`**

This function flips the array in the up-down direction. It is more relevant for multi-dimensional arrays but can be used on a single dimension as well.

Example for a Single Row (2D Array)

In [ ]:
import numpy as np

arr2d = np.array([[1, 2, 3, 4, 5]])
reversedRows = np.flipud(arr2d)

print("Reversed rows using np.flipud():", reversedRows)

Reversed rows using np.flipud(): [[1 2 3 4 5]]


d. **Using `np.fliplr()`**
The `np.fliplr()` function flips the array left to right. This method is specifically for reversing columns in a multi-dimensional array.

Example for a 2D Array

In [ ]:
import numpy as np

arr2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

reversedCols = np.fliplr(arr2d)

print("Original array:\n", arr2d)
print("Reversed columns:\n", reversedCols)

Original array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Reversed columns:
 [[3 2 1]
 [6 5 4]
 [9 8 7]]


## **4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance.**

To determine the data type of elements in a NumPy array, we can use the .dtype attribute of the array. This attribute returns a NumPy data type object that provides information about the type of data stored in the array, such as integer, float, or string types.

**Checking the Data Type of a NumPy array:**

In [ ]:
import numpy as np

# Creating a NumPy array
arr = np.array([1, 2, 3, 4, 5])

# Checking the data type
dataType = arr.dtype
print("Data type of the array:", dataType)

Data type of the array: int64


**Importance of Data Types in Memory Management and Performance**
a. **Memory Efficiency:**

* Each data type in NumPy has a specific size in memory. For instance, int32 uses 4 bytes, while int64 uses 8 bytes. By choosing the appropriate data type for the data, we can significantly reduce memory usage. For large datasets, this can lead to substantial savings in memory consumption.

b. **Performance Optimization:**

* Operations on arrays are optimized based on their data types. NumPy performs computations more efficiently when all elements are of a uniform type. For example, operations on float32 arrays may be faster than those on float64 due to lower memory bandwidth requirements.

* The fixed size of elements allows for better cache utilization and vectorized operations, which can lead to faster execution times compared to Python lists where elements can vary in size and type.

c. **Type Safety:**

* NumPy enforces that all elements in an array must be of the same type. This consistency allows for predictable behavior during computations and reduces errors that may arise from mixed types.

d. **Specialized Operations:**

* Different data types enable specialized mathematical operations that are tailored for specific types of data (e.g., complex numbers or boolean arrays). This capability enhances functionality beyond what is possible with standard Python lists.

e. **Interoperability with Other Libraries:**

* Many scientific computing libraries (like SciPy and Pandas) rely on NumPy's data types for efficient data manipulation and analysis. Understanding and managing these types is crucial when working across different libraries.

## **5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?**

NumPy's ndarray (N-dimensional array) is a core feature of the NumPy library, designed for efficient numerical computations. Here’s a detailed overview of ndarrays, their key features, and how they differ from standard Python lists.

**Definition of ndarrays**

An ndarray is a powerful N-dimensional array object that allows for the storage and manipulation of large datasets in a structured way. It provides a grid-like structure where elements can be accessed using multiple indices, making it suitable for various scientific and mathematical applications.

**Key Features of ndarrays**

a. **Homogeneous Data Types:**
* All elements in an ndarray must be of the same data type (e.g., all integers, all floats). This uniformity allows for optimized performance and memory usage, as the system knows the size and type of each element in advance.

b. **Multidimensional:**
* ndarrays can have any number of dimensions (1D, 2D, 3D, etc.), allowing for complex data structures such as matrices and tensors. This flexibility is essential for handling various data formats in scientific computing.

c. **Efficient Memory Usage:**
* NumPy arrays are stored in contiguous memory locations, which minimizes memory overhead compared to Python lists. This organization enhances cache efficiency and speeds up operations on large datasets.

d. **Vectorized Operations:**

* NumPy supports element-wise operations on arrays without the need for explicit loops. This capability allows for concise and efficient mathematical computations, significantly improving performance over standard Python lists.

e. **Broadcasting:**

* This feature allows NumPy to perform operations on arrays of different shapes by automatically expanding the smaller array to match the larger one’s shape. Broadcasting simplifies code and enhances computational efficiency.

f. **Rich Functionality:**
* ndarrays come with a wide range of built-in mathematical functions and methods for statistical analysis, linear algebra, Fourier transforms, and more, making them versatile tools for data analysis.

g. **Indexing and Slicing:**

* NumPy provides advanced indexing capabilities that allow users to access or modify subsets of data efficiently. This includes boolean indexing and fancy indexing.

**How do ndarrays differ from standard Python lists?**

Here are some key differences:

a. **Data Type:** Python lists can store elements of different data types (e.g., strings, integers, floats), while ndarrays require all elements to be of the same data type.

b. **Size:** Python lists can grow or shrink dynamically, while ndarrays have a fixed size.

c. **Indexing:** Python lists use 0-based indexing, while ndarrays use 0-based indexing for the first dimension and 1-based indexing for subsequent dimensions.

d. **Operations** Python lists support basic operations like indexing, slicing, and concatenation, while ndarrays support more advanced operations like vectorized arithmetic, matrix multiplication, and more.

e. **Memory Usage:** Python lists use more memory than ndarrays because they store references to objects, while ndarrays store the actual data in contiguous blocks of memory.

## **6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.**

When it comes to large-scale numerical operations, NumPy arrays outperform Python lists in several key aspects. Here are the main performance benefits of using NumPy arrays:

a. **Memory Efficiency**

* **Memory Usage:** NumPy arrays store data in a contiguous block of memory, which leads to more efficient memory usage compared to Python lists. This is because Python lists store pointers to individual objects, resulting in higher memory overhead.
* **Memory Allocation:** NumPy arrays allocate memory only once, during initialization, whereas Python lists dynamically allocate memory for each element, leading to slower performance.

b. **Computational Speed**

* **Vectorized Operations:** NumPy arrays support vectorized operations, which allow for operations to be performed on entire arrays at once, rather than iterating over individual elements. This leads to significant speedups for large datasets.

* **C-Based Implementation:** NumPy arrays are implemented in C, which provides a performance boost compared to Python's interpreted nature.

**c. Cache Efficiency**

* **Cache Locality:** NumPy arrays are designed to take advantage of cache locality, which means that the CPU can access data more quickly due to its proximity in memory.

* **Strided Memory Access:** NumPy arrays use strided memory access, which allows for efficient access to elements in memory, reducing the number of cache misses.

**d. Additional Benefits**

* **Broadcasting:** NumPy arrays support broadcasting, which allows for operations to be performed on arrays with different shapes and sizes.
* **Matrix Operations:** NumPy arrays provide optimized implementations of matrix operations, such as matrix multiplication, which are critical in many numerical applications.

**e. When to Use NumPy Arrays**

* **Large-Scale Numerical Operations:** NumPy arrays are ideal for large-scale numerical operations, such as scientific simulations, data analysis, and machine learning.
* **Performance-Critical Applications:** NumPy arrays are suitable for applications where performance is critical, such as real-time data processing or high-performance computing.

**f. When to Use Python Lists**

* **Small-Scale Operations:** Python lists are sufficient for small-scale numerical operations or when memory efficiency is not a concern.
* **Dynamic Data Structures:** Python lists are more suitable for dynamic data structures, such as stacks or queues, where elements are frequently added or removed.


Here is an example demonstrating the memory consumption difference between NumPy arrays and Python lists:

In [ ]:
import sys
import numpy as np

S = range(1000)
print("Size of each element of list in bytes: ", sys.getsizeof(S))
print("Size of the whole list in bytes: ", sys.getsizeof(S) * len(S))

D = np.arange(1000)
print("Size of each element of the Numpy array in bytes: ", D.itemsize)
print("Size of the whole Numpy array in bytes: ", D.size * D.itemsize)

Size of each element of list in bytes:  48
Size of the whole list in bytes:  48000
Size of each element of the Numpy array in bytes:  8
Size of the whole Numpy array in bytes:  8000


The output shows that the NumPy array consumes significantly less memory than the Python list.

Another example demonstrates the time difference between NumPy arrays and Python lists for multiplication operations:

In [ ]:
import numpy as np
import time

size = 1000000
list1 = range(size)
list2 = range(size)
array1 = np.arange(size)
array2 = np.arange(size)

initialTime = time.time()
resultantList = [(a * b) for a, b in zip(list1, list2)]
print("Time taken by Lists to perform multiplication: ", (time.time() - initialTime), "seconds")

initialTime = time.time()
resultantArray = array1 * array2
print("Time taken by NumPy Arrays to perform multiplication: ", (time.time() - initialTime), "seconds")

Time taken by Lists to perform multiplication:  0.1393299102783203 seconds
Time taken by NumPy Arrays to perform multiplication:  0.00926518440246582 seconds


The output shows that NumPy arrays perform multiplication operations significantly faster than Python lists.

In conclusion, NumPy arrays offer substantial performance benefits over Python lists for large-scale numerical operations, making them a preferred choice for scientific computing and data analysis tasks.

## **7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and output.**

**Comparison of `vstack()` and `hstack()` Functions in NumPy**

NumPy provides several functions for stacking arrays, among which `vstack()` and `hstack()` are commonly used. These functions serve different purposes in terms of how they combine arrays.

**Overview of Functions**

* **`numpy.vstack()`:** Stacks arrays vertically (row-wise). It takes a sequence of arrays and combines them into a single array by adding rows.

* **`numpy.hstack()`:** Stacks arrays horizontally (column-wise). It combines arrays by adding columns, effectively concatenating them along the second axis.

**Syntax**

* **`vstack():`**
```
numpy.vstack(tup)
```

* **`hstack()`:**
```
numpy.hstack(tup)
```

**Requirements**

For both functions, the input arrays must have compatible shapes:

* `vstack()` requires that all input arrays have the same number of columns.
* `hstack()` requires that all input arrays have the same number of rows

Examples

Example 1: Using `vstack()`


In [ ]:
import numpy as np

# Creating two 1-D arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Stacking vertically
resultV = np.vstack((a, b))
print(resultV)

[[1 2 3]
 [4 5 6]]


In this example, `vstack()` combines the two 1-D arrays into a 2-D array with two rows.

Example 2: Using `hstack()`

In [ ]:
import numpy as np

# Creating two 1-D arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Stacking horizontally
resultH = np.hstack((a, b))
print(resultH)

[1 2 3 4 5 6]


Here, `hstack()` combines the two arrays into a single row.

Example 3: Stacking Higher Dimensional Arrays

`Using vstack()`

In [ ]:
import numpy as np

# Creating two 2-D arrays
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

# Stacking vertically
resultV2 = np.vstack((a, b))
print(resultV2)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


Using `hstack()`

In [ ]:
import numpy as np

# Creating two compatible 2-D arrays
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

# Stacking horizontally
resultH2 = np.hstack((a, b))
print(resultH2)

[[1 2 5 6]
 [3 4 7 8]]


## **8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various array dimensions.**


The `fliplr()` and `flipud()` methods in NumPy are used to flip arrays horizontally and vertically, respectively. While they may seem similar, they have distinct effects on arrays with different dimensions.

`fliplr()` - Flip Left-Right

The fliplr() function flips an array horizontally, i.e., it reverses the elements in each row. This means that the elements in the leftmost column become the rightmost column, and vice versa.


###Effects on various array dimensions:

* `1-D array:` fliplr() has no effect on a 1-D array, as there is only one row.
* `2-D array:` fliplr() flips the array horizontally, reversing the columns.
* `3-D array:` fliplr() flips each 2-D slice in the array horizontally.

Let's take an example.




In [ ]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print("Original array:\n", arr)

flippedArr = np.fliplr(arr)
print("Flipped array (horizontal):\n", flippedArr)

Original array:
 [[1 2 3 4]
 [5 6 7 8]]
Flipped array (horizontal):
 [[4 3 2 1]
 [8 7 6 5]]


`flipud() - Flip Up-Down`

The flipud() function flips an array vertically, i.e., it reverses the elements in each column. This means that the elements in the topmost row become the bottommost row, and vice versa


###Effects on various array dimensions:

* 1-D array: flipud() has no effect on a 1-D array, as there is only one column.
* 2-D array: flipud() flips the array vertically, reversing the rows.
* 3-D array: flipud() flips each 2-D slice in the array vertically.

Let's take an example:

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print("Original array:\n", arr)

flippedArr = np.flipud(arr)
print("Flipped array (vertical):\n", flippedArr)


Original array:
 [[1 2 3 4]
 [5 6 7 8]]
Flipped array (vertical):
 [[5 6 7 8]
 [1 2 3 4]]


##**9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?**

The `numpy.array_split()` method is a versatile function in NumPy that allows users to split an array into multiple sub-arrays. Here’s a detailed overview of its functionality, including how it handles uneven splits.

Functionality:

###The array_split() function takes three main arguments:

* `ary`: The input array to be split.

* `indices_or_sections`: The number of sections to split the array into. If an integer is provided, the array is split into equal-sized sections. If a list of indices is provided, the array is split at those specific indices.
* `axis`: The axis along which to split the array.


###`Handling uneven splits:`

When the `indices_or_sections` argument is an integer, `array_split()` attempts to split the array into equal-sized sections. However, if the length of the array is not exactly divisible by the number of sections, the remaining elements are distributed unevenly among the sections.


Let's take an example:


In [ ]:
import numpy as np
a = np.arange(9)  # Creates an array [0, 1, 2, 3, 4, 5, 6, 7, 8]
result = np.array_split(a, 4)
print(result)

[array([0, 1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]


* Here, the original array has 9 elements and is split into 4 parts. The first three sub-arrays have three elements each, while the last one has two elements.

###`Specifying indices for uneven splits:`

If we need more control over the split points, we can provide a list of indices instead of an integer. This allows us to specify exactly where the array should be split.



In [ ]:
import numpy as np

arr = np.arange(10)
splitArr = np.array_split(arr, [3, 7])

print("Original array:", arr)
print("Split array:")
for i, sub_arr in enumerate(splitArr):
    print(f"Section {i+1}: {sub_arr}")

Original array: [0 1 2 3 4 5 6 7 8 9]
Split array:
Section 1: [0 1 2]
Section 2: [3 4 5 6]
Section 3: [7 8 9]


In this example, the array is split at indices 3 and 7, resulting in three sections with different sizes.


##**10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?**

Vectorization and broadcasting are two fundamental concepts in NumPy that enable efficient array operations. These concepts allow NumPy to perform operations on entire arrays at once, rather than iterating over individual elements, making it a powerful tool for numerical computations.

###**Vectorization**

Vectorization is the process of performing operations on entire arrays at once, rather than iterating over individual elements. This is achieved through the use of universal functions (ufuncs), which are functions that operate on entire arrays. Ufuncs take advantage of the fact that many operations can be applied element-wise to entire arrays, eliminating the need for loops.

In NumPy, vectorization is achieved through the use of operators and functions that operate on entire arrays. For example, when we add two arrays together, NumPy performs the operation element-wise, without the need for explicit loops.




In [ ]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

result = arr1 + arr2
print(result)

[5 7 9]


In this example, the + operator is applied element-wise to the two arrays, resulting in a new array with the summed values.

###**Broadcasting**

Broadcasting is a mechanism that allows NumPy to perform operations on arrays with different shapes and sizes. It enables the alignment of arrays with different dimensions, allowing operations to be performed on corresponding elements.

Broadcasting occurs when we perform an operation on two arrays with different shapes. NumPy aligns the arrays by adding dimensions of size 1 to the smaller array, allowing the operation to be performed element-wise.

Let's take an example:

In [ ]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([[4], [5], [6]])

result = arr1 + arr2
print(result)

[[5 6 7]
 [6 7 8]
 [7 8 9]]


In this example, the `+` operator is applied element-wise to the two arrays, despite their different shapes. NumPy broadcasts the smaller array to match the shape of the larger array, allowing the operation to be performed.


###**Contribution to Efficient Array Operations**

Vectorization and broadcasting contribute to efficient array operations in several ways:

* `Reduced Looping`: Vectorization eliminates the need for explicit loops, reducing the overhead of iterating over individual elements.

* `Parallelization`: NumPy can take advantage of parallel processing capabilities, performing operations on entire arrays at once.

* `Memory Efficiency`: Broadcasting allows NumPy to perform operations on arrays with different shapes, reducing the need for intermediate arrays and minimizing memory allocation.

* `Improved Performance`: Vectorization and broadcasting enable NumPy to perform operations at a lower level, closer to the machine language, resulting in faster execution times.

#**Practical Questions:**

##**1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.**


In [ ]:
import numpy as np

# Create a 3x3 NumPy array with random integers between 1 and 100
arr = np.random.randint(1, 101, (3, 3))
print("Original array:")
print(arr)

# Interchange rows and columns using the transpose function
arrTransposed = arr.transpose()
print("\nTransposed array:")
print(arrTransposed)

Original array:
[[18 56 97]
 [ 4  3 57]
 [10 30  3]]

Transposed array:
[[18  4 10]
 [56  3 30]
 [97 57  3]]


##**2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array**


In [ ]:
import numpy as np

# Generate a 1D NumPy array with 10 elements
arr = np.arange(1, 11)
print("Original 1D array:")
print(arr)

# Reshape into a 2x5 array
arr2x5 = arr.reshape(2, 5)
print("\nReshaped 2x5 array:")
print(arr2x5)

# Reshape into a 5x2 array
arr5x2 = arr.reshape(5, 2)
print("\nReshaped 5x2 array:")
print(arr5x2)

Original 1D array:
[ 1  2  3  4  5  6  7  8  9 10]

Reshaped 2x5 array:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

Reshaped 5x2 array:
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


##**3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.**





In [ ]:
import numpy as np

arr = np.random.rand(4, 4)
print("Original 4x4 array:")
print(arr)

arrWithBorder = np.pad(arr, 1, mode='constant')
print("\n6x6 array with border of zeros:")
print(arrWithBorder)

Original 4x4 array:
[[0.45029246 0.88217222 0.4616114  0.71279891]
 [0.64889438 0.24704252 0.64457593 0.51265691]
 [0.83730086 0.90364202 0.3903446  0.53521761]
 [0.10381638 0.96475781 0.4875199  0.60247158]]

6x6 array with border of zeros:
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.45029246 0.88217222 0.4616114  0.71279891 0.        ]
 [0.         0.64889438 0.24704252 0.64457593 0.51265691 0.        ]
 [0.         0.83730086 0.90364202 0.3903446  0.53521761 0.        ]
 [0.         0.10381638 0.96475781 0.4875199  0.60247158 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


##**4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.**



In [ ]:
import numpy as np
array = np.arange(10,  61, 5)

print(array)

[10 15 20 25 30 35 40 45 50 55 60]


##**5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformation(uppercase, lowercase, title case, etc.) to each element**





In [ ]:
import numpy as np

array = np.array(['python', 'numpy', 'pandas'])

# Uppercase
uppercaseArray = np.char.upper(array)
print("Uppercase:", uppercaseArray)

# Lowercase
lowercaseArray = np.char.lower(array)
print("Lowercase:", lowercaseArray)

# Title case
titlecaseArray = np.char.title(array)
print("Title case:", titlecaseArray)

# Swapcase
swapcaseArray = np.char.swapcase(array)
print("Swapcase:", swapcaseArray)

Uppercase: ['PYTHON' 'NUMPY' 'PANDAS']
Lowercase: ['python' 'numpy' 'pandas']
Title case: ['Python' 'Numpy' 'Pandas']
Swapcase: ['PYTHON' 'NUMPY' 'PANDAS']


##**6. Generate a NumPy array of words. Insert a space between each character of every word in the array.**

In [ ]:
import numpy as np
array = np.array(['python', 'numpy', 'pandas'])
result = np.char.join(' ', array)

print(result)

['p y t h o n' 'n u m p y' 'p a n d a s']


##**7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.**

In [ ]:
import numpy as np
# Create two 2D NumPy arrays
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

# Element-wise addition
additionResult = array1 + array2
print("Element-wise addition:")
print(additionResult)

# Element-wise subtraction
subtractionResult = array1 - array2
print("Element-wise subtraction:")
print(subtractionResult)

# Element-wise multiplication
multiplicationResult = array1 * array2
print("Element-wise multiplication:")
print(multiplicationResult)

# Element-wise division
divisionResult = array1 / array2
print("Element-wise division:")
print(divisionResult)

Element-wise addition:
[[ 6  8]
 [10 12]]
Element-wise subtraction:
[[-4 -4]
 [-4 -4]]
Element-wise multiplication:
[[ 5 12]
 [21 32]]
Element-wise division:
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


##**8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.**


In [ ]:
import numpy as np


# Create a 5x5 identity matrix
identityMatrix = np.eye(5)
print("Identity matrix:")
print(identityMatrix)

# Extract the diagonal elements
diagonalElements = np.diag(identityMatrix)
print("Diagonal elements:", diagonalElements)

Identity matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Diagonal elements: [1. 1. 1. 1. 1.]


##**9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.**



In [ ]:
import numpy as np

array = np.random.randint(0, 1001, 100)


def isPrime(n):
    if n <= 1:
        return False
    if n == 2:
        return True
    if n % 2 == 0:
        return False
    maxdivisor = int(n**0.5) + 1
    for d in range(3, maxdivisor, 2):
        if n % d == 0:
            return False
    return True

primenNumbers = array[np.vectorize(isPrime)(array)]
print("Prime numbers:", primenNumbers)

Prime numbers: [383 733 743 823 983 263 887 439  17 587 563 269 359  19 337 431 241]


##**10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.**


In [ ]:
import numpy as np
dailyTemperatures = np.random.uniform(20, 35, 30)
weeks = np.split(dailyTemperatures, [7, 14, 21, 28])
weeklyAverages = [np.mean(week) for week in weeks]

for i, avg in enumerate(weeklyAverages):
    print(f"Week {i+1} average temperature: {avg:.2f}°C")

Week 1 average temperature: 25.82°C
Week 2 average temperature: 28.34°C
Week 3 average temperature: 28.57°C
Week 4 average temperature: 28.97°C
Week 5 average temperature: 20.65°C
